//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Dominion.Resources
{
    using System;
    using System.Reflection;
    using System.Threading;
    using Windows.ApplicationModel.Core;
    using Windows.ApplicationModel.Resources.Core;
    using Windows.UI.Core;
    using Windows.UI.Xaml;
    
    
    public partial class CardDataStrings
    {
        
        private static ResourceContext _context;
        
        private static ResourceMap _map;
        
        static CardDataStrings()
        {
            _context = CreateContext();
            _map = CreateMap<CardDataStrings>();
        }
        
        public static ResourceContext Context
        {
            get
            {
                return _context;
            }
        }
        
        public static ResourceMap Map
        {
            get
            {
                return _map;
            }
        }
        
        public static string Application_LocalizedCardsFileName
        {
            get
            {
                return GetString("Application_LocalizedCardsFileName");
            }
        }
        
        /// <example>
        /// Adventures
        /// </example>
        public static string CardSet_Adventures
        {
            get
            {
                return GetString("CardSet_Adventures");
            }
        }
        
        /// <example>
        /// Alchemy
        /// </example>
        public static string CardSet_Alchemy
        {
            get
            {
                return GetString("CardSet_Alchemy");
            }
        }
        
        /// <example>
        /// Base
        /// </example>
        public static string CardSet_Base
        {
            get
            {
                return GetString("CardSet_Base");
            }
        }
        
        /// <example>
        /// Base 2E
        /// </example>
        public static string CardSet_Base2E
        {
            get
            {
                return GetString("CardSet_Base2E");
            }
        }
        
        /// <example>
        /// Cornucopia
        /// </example>
        public static string CardSet_Cornucopia
        {
            get
            {
                return GetString("CardSet_Cornucopia");
            }
        }
        
        /// <example>
        /// Dark Ages
        /// </example>
        public static string CardSet_DarkAges
        {
            get
            {
                return GetString("CardSet_DarkAges");
            }
        }
        
        /// <example>
        /// Empires
        /// </example>
        public static string CardSet_Empires
        {
            get
            {
                return GetString("CardSet_Empires");
            }
        }
        
        /// <example>
        /// Guilds
        /// </example>
        public static string CardSet_Guilds
        {
            get
            {
                return GetString("CardSet_Guilds");
            }
        }
        
        /// <example>
        /// Hinterlands
        /// </example>
        public static string CardSet_Hinterlands
        {
            get
            {
                return GetString("CardSet_Hinterlands");
            }
        }
        
        /// <example>
        /// Intrigue
        /// </example>
        public static string CardSet_Intrigue
        {
            get
            {
                return GetString("CardSet_Intrigue");
            }
        }
        
        /// <example>
        /// Intrigue 2E
        /// </example>
        public static string CardSet_Intrigue2E
        {
            get
            {
                return GetString("CardSet_Intrigue2E");
            }
        }
        
        /// <example>
        /// Promo
        /// </example>
        public static string CardSet_Promo
        {
            get
            {
                return GetString("CardSet_Promo");
            }
        }
        
        /// <example>
        /// Prosperity
        /// </example>
        public static string CardSet_Prosperity
        {
            get
            {
                return GetString("CardSet_Prosperity");
            }
        }
        
        /// <example>
        /// Seaside
        /// </example>
        public static string CardSet_Seaside
        {
            get
            {
                return GetString("CardSet_Seaside");
            }
        }
        
        /// <example>
        /// Action
        /// </example>
        public static string CardType_Action
        {
            get
            {
                return GetString("CardType_Action");
            }
        }
        
        /// <example>
        /// Attack
        /// </example>
        public static string CardType_Attack
        {
            get
            {
                return GetString("CardType_Attack");
            }
        }
        
        /// <example>
        /// Curse
        /// </example>
        public static string CardType_Curse
        {
            get
            {
                return GetString("CardType_Curse");
            }
        }
        
        /// <example>
        /// Duration
        /// </example>
        public static string CardType_Duration
        {
            get
            {
                return GetString("CardType_Duration");
            }
        }
        
        /// <example>
        /// Event
        /// </example>
        public static string CardType_Event
        {
            get
            {
                return GetString("CardType_Event");
            }
        }
        
        /// <example>
        /// Knight
        /// </example>
        public static string CardType_Knight
        {
            get
            {
                return GetString("CardType_Knight");
            }
        }
        
        /// <example>
        /// Landmark
        /// </example>
        public static string CardType_Landmark
        {
            get
            {
                return GetString("CardType_Landmark");
            }
        }
        
        /// <example>
        /// Looter
        /// </example>
        public static string CardType_Looter
        {
            get
            {
                return GetString("CardType_Looter");
            }
        }
        
        /// <example>
        /// Prize
        /// </example>
        public static string CardType_Prize
        {
            get
            {
                return GetString("CardType_Prize");
            }
        }
        
        /// <example>
        /// Reaction
        /// </example>
        public static string CardType_Reaction
        {
            get
            {
                return GetString("CardType_Reaction");
            }
        }
        
        /// <example>
        /// Reserve
        /// </example>
        public static string CardType_Reserve
        {
            get
            {
                return GetString("CardType_Reserve");
            }
        }
        
        /// <example>
        /// Ruins
        /// </example>
        public static string CardType_Ruins
        {
            get
            {
                return GetString("CardType_Ruins");
            }
        }
        
        /// <example>
        /// Shelter
        /// </example>
        public static string CardType_Shelter
        {
            get
            {
                return GetString("CardType_Shelter");
            }
        }
        
        /// <example>
        /// Traveller
        /// </example>
        public static string CardType_Traveller
        {
            get
            {
                return GetString("CardType_Traveller");
            }
        }
        
        /// <example>
        /// Treasure
        /// </example>
        public static string CardType_Treasure
        {
            get
            {
                return GetString("CardType_Treasure");
            }
        }
        
        /// <example>
        /// Victory
        /// </example>
        public static string CardType_Victory
        {
            get
            {
                return GetString("CardType_Victory");
            }
        }
        
        private static ResourceContext CreateContext()
        {
            var dispatcher = default(CoreDispatcher);
            var window = Window.Current;
            if ((window != null))
            {
                dispatcher = window.Dispatcher;
            }
            if ((dispatcher == null))
            {
                var mainView = CoreApplication.MainView;
                if ((mainView != null))
                {
                    dispatcher = mainView.Dispatcher;
                }
            }
            return CreateContext(dispatcher);
        }
        
        private static ResourceContext CreateContext(CoreDispatcher dispatcher)
        {
            if ((dispatcher != null))
            {
                if (dispatcher.HasThreadAccess)
                {
                    return ResourceContext.GetForCurrentView();
                }
                var cancellationTokenSource = new CancellationTokenSource();
                try
                {
                    var context = default(ResourceContext);
                    var action = dispatcher.RunAsync(CoreDispatcherPriority.High, () => context = ResourceContext.GetForCurrentView());
                    var task = WindowsRuntimeSystemExtensions.AsTask(action, cancellationTokenSource.Token);
                    // Runs into a 'timeout', when the 'main-thread' is blocked recently.
                    // Don't wait too long as there is an alternative way to retrieve an context (for independent use).
                    task.Wait(TimeSpan.FromSeconds(1));
                    cancellationTokenSource.Cancel();
                    if ((context != null))
                    {
                        return context;
                    }
                }
                finally
                {
                    cancellationTokenSource.Dispose();
                }
            }
            return ResourceContext.GetForViewIndependentUse();
        }
        
        public static ResourceMap CreateMap<T>()
            where T :  class
        {
            var applicationAssemblyName = Application.Current.GetType().GetTypeInfo().Assembly.GetName().Name;
            var type = typeof(T);
            var assemblyName = type.GetTypeInfo().Assembly.GetName().Name;
            string resourceName;
            if (applicationAssemblyName.Equals(assemblyName))
            {
                resourceName = type.Name;
            }
            else
            {
                resourceName = (assemblyName 
                            + ("/" + type.Name));
            }
            return ResourceManager.Current.MainResourceMap.GetSubtree(resourceName);
        }
        
        private static string GetString(string propertyName)
        {
            return Map.GetValue(propertyName, Context).ValueAsString;
        }
    }
}
