//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Dominion.Resources
{
    using System;
    using System.Reflection;
    using System.Threading;
    using Windows.ApplicationModel.Core;
    using Windows.ApplicationModel.Resources.Core;
    using Windows.UI.Core;
    using Windows.UI.Xaml;
    
    
    public partial class Strings
    {
        
        private static ResourceContext _context;
        
        private static ResourceMap _map;
        
        static Strings()
        {
            System.Diagnostics.Debug.WriteLine("Initializing Strings");
            _context = CreateContext();
            _map = CreateMap<Strings>();
        }
        
        public static ResourceContext Context
        {
            get
            {
                return _context;
            }
        }
        
        public static ResourceMap Map
        {
            get
            {
                return _map;
            }
        }
        
        /// <example>
        /// about
        /// </example>
        public static string About_About
        {
            get
            {
                return GetString("About_About");
            }
        }
        
        /// <example>
        /// changes
        /// </example>
        public static string About_Changes
        {
            get
            {
                return GetString("About_Changes");
            }
        }
        
        /// <example>
        /// help
        /// </example>
        public static string About_Help
        {
            get
            {
                return GetString("About_Help");
            }
        }
        
        /// <example>
        /// rate/review
        /// </example>
        public static string About_Rate
        {
            get
            {
                return GetString("About_Rate");
            }
        }
        
        /// <example>
        /// rules
        /// </example>
        public static string About_Rules
        {
            get
            {
                return GetString("About_Rules");
            }
        }
        
        /// <example>
        /// Download PDFs of the full versions of the Dominion Rules for each set.  The files are saved locally for quick access any time later.
        /// </example>
        public static string About_RulesDescription
        {
            get
            {
                return GetString("About_RulesDescription");
            }
        }
        
        /// <example>
        /// update
        /// </example>
        public static string About_Update
        {
            get
            {
                return GetString("About_Update");
            }
        }
        
        /// <example>
        /// settings
        /// </example>
        public static string Application_Settings
        {
            get
            {
                return GetString("Application_Settings");
            }
        }
        
        /// <example>
        /// Dominion Picker
        /// </example>
        public static string Application_Title
        {
            get
            {
                return GetString("Application_Title");
            }
        }
        
        /// <example>
        /// black market
        /// </example>
        public static string BlackMarket_Title
        {
            get
            {
                return GetString("BlackMarket_Title");
            }
        }
        
        /// <example>
        /// bane for {0}
        /// </example>
        public static string CardGroupType_BaneRequired
        {
            get
            {
                return GetString("CardGroupType_BaneRequired");
            }
        }
        
        /// <example>
        /// SHOULD NOT USE
        /// </example>
        public static string CardGroupType_CurseRequired
        {
            get
            {
                return GetString("CardGroupType_CurseRequired");
            }
        }
        
        /// <example>
        /// events/landmarks
        /// </example>
        public static string CardGroupType_Events
        {
            get
            {
                return GetString("CardGroupType_Events");
            }
        }
        
        /// <example>
        /// kingdom cards
        /// </example>
        public static string CardGroupType_KingdomCard
        {
            get
            {
                return GetString("CardGroupType_KingdomCard");
            }
        }
        
        /// <example>
        /// required by {0}
        /// </example>
        public static string CardGroupType_OtherRequired
        {
            get
            {
                return GetString("CardGroupType_OtherRequired");
            }
        }
        
        /// <example>
        /// selected because you're using Dark Ages
        /// </example>
        public static string CardGroupType_SelectedDarkAges
        {
            get
            {
                return GetString("CardGroupType_SelectedDarkAges");
            }
        }
        
        /// <example>
        /// selected because you're using Prosperity
        /// </example>
        public static string CardGroupType_SelectedProsperity
        {
            get
            {
                return GetString("CardGroupType_SelectedProsperity");
            }
        }
        
        /// <example>
        /// No Preference
        /// </example>
        public static string CardRequirementOption_NoPreference
        {
            get
            {
                return GetString("CardRequirementOption_NoPreference");
            }
        }
        
        public static string CardRequirementOption_NoPreference_Description
        {
            get
            {
                return GetString("CardRequirementOption_NoPreference_Description");
            }
        }
        
        /// <example>
        /// Prevent All
        /// </example>
        public static string CardRequirementOption_Prevent
        {
            get
            {
                return GetString("CardRequirementOption_Prevent");
            }
        }
        
        public static string CardRequirementOption_Prevent_Description
        {
            get
            {
                return GetString("CardRequirementOption_Prevent_Description");
            }
        }
        
        /// <example>
        /// Prevent All +2
        /// </example>
        public static string CardRequirementOption_PreventPlus2
        {
            get
            {
                return GetString("CardRequirementOption_PreventPlus2");
            }
        }
        
        public static string CardRequirementOption_PreventPlus2_Description
        {
            get
            {
                return GetString("CardRequirementOption_PreventPlus2_Description");
            }
        }
        
        /// <example>
        /// Require At Least One
        /// </example>
        public static string CardRequirementOption_Require
        {
            get
            {
                return GetString("CardRequirementOption_Require");
            }
        }
        
        public static string CardRequirementOption_Require_Description
        {
            get
            {
                return GetString("CardRequirementOption_Require_Description");
            }
        }
        
        /// <example>
        /// Require At Least One +2
        /// </example>
        public static string CardRequirementOption_RequirePlus2
        {
            get
            {
                return GetString("CardRequirementOption_RequirePlus2");
            }
        }
        
        public static string CardRequirementOption_RequirePlus2_Description
        {
            get
            {
                return GetString("CardRequirementOption_RequirePlus2_Description");
            }
        }
        
        /// <example>
        /// Card Details
        /// </example>
        public static string Config_CardData
        {
            get
            {
                return GetString("Config_CardData");
            }
        }
        
        public static string Config_CardDataDesc
        {
            get
            {
                return GetString("Config_CardDataDesc");
            }
        }
        
        /// <example>
        /// when to pick Events
        /// </example>
        public static string Config_EventsOption
        {
            get
            {
                return GetString("Config_EventsOption");
            }
        }
        
        /// <example>
        /// language
        /// </example>
        public static string Config_Language
        {
            get
            {
                return GetString("Config_Language");
            }
        }
        
        /// <example>
        /// Setting this will override the language used by Dominion Picker only and will not change the current system language.
        ///You must restart for this to take effect.
        /// </example>
        public static string Config_LanguageDescription
        {
            get
            {
                return GetString("Config_LanguageDescription");
            }
        }
        
        /// <example>
        /// Language Options
        /// </example>
        public static string Config_LanguageOptions
        {
            get
            {
                return GetString("Config_LanguageOptions");
            }
        }
        
        /// <example>
        /// sets that I own
        /// </example>
        public static string Config_OwnedSets
        {
            get
            {
                return GetString("Config_OwnedSets");
            }
        }
        
        /// <example>
        /// Specify which sets you own and would like to be able to pick from.  Sets not included here will never be used during selection or for any additional reasons such as the Black Market deck.
        /// </example>
        public static string Config_OwnedSetsDescription
        {
            get
            {
                return GetString("Config_OwnedSetsDescription");
            }
        }
        
        /// <example>
        /// Picker Options
        /// </example>
        public static string Config_PickerOptions
        {
            get
            {
                return GetString("Config_PickerOptions");
            }
        }
        
        /// <example>
        /// when to pick Platinum and Colony
        /// </example>
        public static string Config_PlatinumColonyOption
        {
            get
            {
                return GetString("Config_PlatinumColonyOption");
            }
        }
        
        /// <example>
        /// Cards with +Action
        /// </example>
        public static string Config_PlusActions
        {
            get
            {
                return GetString("Config_PlusActions");
            }
        }
        
        /// <example>
        /// Cards with +Buy
        /// </example>
        public static string Config_PlusBuys
        {
            get
            {
                return GetString("Config_PlusBuys");
            }
        }
        
        /// <example>
        /// Rules Text
        /// </example>
        public static string Config_RulesText
        {
            get
            {
                return GetString("Config_RulesText");
            }
        }
        
        public static string Config_RulesTextDesc
        {
            get
            {
                return GetString("Config_RulesTextDesc");
            }
        }
        
        /// <example>
        /// when to pick Shelters or Estates
        /// </example>
        public static string Config_SheltersOption
        {
            get
            {
                return GetString("Config_SheltersOption");
            }
        }
        
        /// <example>
        /// settings
        /// </example>
        public static string Config_Title
        {
            get
            {
                return GetString("Config_Title");
            }
        }
        
        /// <example>
        /// User Interface
        /// </example>
        public static string Config_UI
        {
            get
            {
                return GetString("Config_UI");
            }
        }
        
        public static string Config_UIDesc
        {
            get
            {
                return GetString("Config_UIDesc");
            }
        }
        
        /// <example>
        /// Coin Token
        /// </example>
        public static string Dominion_CoinToken
        {
            get
            {
                return GetString("Dominion_CoinToken");
            }
        }
        
        /// <example>
        /// Emargo Token
        /// </example>
        public static string Dominion_EmargoToken
        {
            get
            {
                return GetString("Dominion_EmargoToken");
            }
        }
        
        /// <example>
        /// Island Mat
        /// </example>
        public static string Dominion_IslandMat
        {
            get
            {
                return GetString("Dominion_IslandMat");
            }
        }
        
        /// <example>
        /// Mat
        /// </example>
        public static string Dominion_Mat
        {
            get
            {
                return GetString("Dominion_Mat");
            }
        }
        
        /// <example>
        /// Native Village Mat
        /// </example>
        public static string Dominion_NativeVillageMat
        {
            get
            {
                return GetString("Dominion_NativeVillageMat");
            }
        }
        
        /// <example>
        /// Pirate Ship Mat
        /// </example>
        public static string Dominion_PirateMat
        {
            get
            {
                return GetString("Dominion_PirateMat");
            }
        }
        
        /// <example>
        /// Token
        /// </example>
        public static string Dominion_Token
        {
            get
            {
                return GetString("Dominion_Token");
            }
        }
        
        /// <example>
        /// Always select Events
        /// </example>
        public static string EventsOption_Always
        {
            get
            {
                return GetString("EventsOption_Always");
            }
        }
        
        /// <example>
        /// The result will always include two randomly selected Events.
        /// </example>
        public static string EventsOption_Always_Description
        {
            get
            {
                return GetString("EventsOption_Always_Description");
            }
        }
        
        /// <example>
        /// Always when using a set with Events
        /// </example>
        public static string EventsOption_AlwaysWithSet
        {
            get
            {
                return GetString("EventsOption_AlwaysWithSet");
            }
        }
        
        /// <example>
        /// If you are using a set that contains Events, the result will always include two randomly selected Events.
        /// </example>
        public static string EventsOption_AlwaysWithSet_Description
        {
            get
            {
                return GetString("EventsOption_AlwaysWithSet_Description");
            }
        }
        
        /// <example>
        /// Never select events
        /// </example>
        public static string EventsOption_Never
        {
            get
            {
                return GetString("EventsOption_Never");
            }
        }
        
        /// <example>
        /// Never select any Events.
        /// </example>
        public static string EventsOption_Never_Description
        {
            get
            {
                return GetString("EventsOption_Never_Description");
            }
        }
        
        /// <example>
        /// Randomly select 
        /// </example>
        public static string EventsOption_Randomly
        {
            get
            {
                return GetString("EventsOption_Randomly");
            }
        }
        
        /// <example>
        /// The result will include between zero and two randomly selected Events.
        /// </example>
        public static string EventsOption_Randomly_Description
        {
            get
            {
                return GetString("EventsOption_Randomly_Description");
            }
        }
        
        /// <example>
        /// Randomly when using a set with Events
        /// </example>
        public static string EventsOption_RandomlyWithSet
        {
            get
            {
                return GetString("EventsOption_RandomlyWithSet");
            }
        }
        
        /// <example>
        /// If you are using a set that contains Events, the result will include between zero and two randomly selected Events.
        /// </example>
        public static string EventsOption_RandomlyWithSet_Description
        {
            get
            {
                return GetString("EventsOption_RandomlyWithSet_Description");
            }
        }
        
        /// <example>
        /// delete
        /// </example>
        public static string Favorites_Delete
        {
            get
            {
                return GetString("Favorites_Delete");
            }
        }
        
        /// <example>
        /// edit
        /// </example>
        public static string Favorites_Edit
        {
            get
            {
                return GetString("Favorites_Edit");
            }
        }
        
        /// <example>
        /// No favorite sets saved yet. Try using one of the randomizers above to create one.
        /// </example>
        public static string Favorites_NoSets
        {
            get
            {
                return GetString("Favorites_NoSets");
            }
        }
        
        /// <example>
        /// No favorite randomizers saved yet.  Check out the create page to add one.
        /// </example>
        public static string Favorites_NoSettings
        {
            get
            {
                return GetString("Favorites_NoSettings");
            }
        }
        
        /// <example>
        /// rename
        /// </example>
        public static string Favorites_Rename
        {
            get
            {
                return GetString("Favorites_Rename");
            }
        }
        
        /// <example>
        /// Enjoy a set? Save it so you can try it again!
        /// </example>
        public static string Favorites_SetsDesc
        {
            get
            {
                return GetString("Favorites_SetsDesc");
            }
        }
        
        /// <example>
        /// Card Sets
        /// </example>
        public static string Favorites_SetsTitle
        {
            get
            {
                return GetString("Favorites_SetsTitle");
            }
        }
        
        /// <example>
        /// Save your settings to quickly reuse them later.
        /// </example>
        public static string Favorites_SettingsDesc
        {
            get
            {
                return GetString("Favorites_SettingsDesc");
            }
        }
        
        /// <example>
        /// Card Randomizers
        /// </example>
        public static string Favorites_SettingsTitle
        {
            get
            {
                return GetString("Favorites_SettingsTitle");
            }
        }
        
        /// <example>
        /// rules
        /// </example>
        public static string Info_Rules
        {
            get
            {
                return GetString("Info_Rules");
            }
        }
        
        /// <example>
        /// set
        /// </example>
        public static string Info_Set
        {
            get
            {
                return GetString("Info_Set");
            }
        }
        
        /// <example>
        /// Swipe to view
        ///other cards
        /// </example>
        public static string Info_Tips
        {
            get
            {
                return GetString("Info_Tips");
            }
        }
        
        /// <example>
        /// card info
        /// </example>
        public static string Info_Title
        {
            get
            {
                return GetString("Info_Title");
            }
        }
        
        /// <example>
        /// type
        /// </example>
        public static string Info_Type
        {
            get
            {
                return GetString("Info_Type");
            }
        }
        
        /// <example>
        /// strategy wiki
        /// </example>
        public static string Info_Wiki
        {
            get
            {
                return GetString("Info_Wiki");
            }
        }
        
        /// <example>
        /// Reset Filtered Cards
        /// </example>
        public static string Lookup_ResetFiltered
        {
            get
            {
                return GetString("Lookup_ResetFiltered");
            }
        }
        
        /// <example>
        /// Filter by Name, Set, Type, Rules
        /// </example>
        public static string Lookup_SearchHint
        {
            get
            {
                return GetString("Lookup_SearchHint");
            }
        }
        
        /// <example>
        /// Show Filtered Cards
        /// </example>
        public static string Lookup_ShowFiltered
        {
            get
            {
                return GetString("Lookup_ShowFiltered");
            }
        }
        
        /// <example>
        /// Checked cards will
        ///never be picked
        /// </example>
        public static string Lookup_Tips
        {
            get
            {
                return GetString("Lookup_Tips");
            }
        }
        
        /// <example>
        /// card list
        /// </example>
        public static string Lookup_Title
        {
            get
            {
                return GetString("Lookup_Title");
            }
        }
        
        /// <example>
        /// additional options
        /// </example>
        public static string MainPage_AddnOptions
        {
            get
            {
                return GetString("MainPage_AddnOptions");
            }
        }
        
        /// <example>
        /// create
        /// </example>
        public static string MainPage_Create
        {
            get
            {
                return GetString("MainPage_Create");
            }
        }
        
        /// <example>
        /// favorites
        /// </example>
        public static string MainPage_Favorites
        {
            get
            {
                return GetString("MainPage_Favorites");
            }
        }
        
        /// <example>
        /// Generate Set
        /// </example>
        public static string MainPage_GenerateButton
        {
            get
            {
                return GetString("MainPage_GenerateButton");
            }
        }
        
        /// <example>
        /// Generating card set...
        /// </example>
        public static string MainPage_Generating
        {
            get
            {
                return GetString("MainPage_Generating");
            }
        }
        
        /// <example>
        /// reset
        /// </example>
        public static string MainPage_Reset
        {
            get
            {
                return GetString("MainPage_Reset");
            }
        }
        
        /// <example>
        /// save...
        /// </example>
        public static string MainPage_Save
        {
            get
            {
                return GetString("MainPage_Save");
            }
        }
        
        /// <example>
        /// Help/About
        /// </example>
        public static string Menu_About
        {
            get
            {
                return GetString("Menu_About");
            }
        }
        
        /// <example>
        /// Black Market Deck
        /// </example>
        public static string Menu_BlackMarket
        {
            get
            {
                return GetString("Menu_BlackMarket");
            }
        }
        
        /// <example>
        /// Card Lookup/Filter
        /// </example>
        public static string Menu_CardLookup
        {
            get
            {
                return GetString("Menu_CardLookup");
            }
        }
        
        /// <example>
        /// Settings
        /// </example>
        public static string Menu_Settings
        {
            get
            {
                return GetString("Menu_Settings");
            }
        }
        
        /// <example>
        /// Always use them
        /// </example>
        public static string PlatinumColonyOption_Always
        {
            get
            {
                return GetString("PlatinumColonyOption_Always");
            }
        }
        
        /// <example>
        /// Always show Platinum and Colony in the list of required cards.
        /// </example>
        public static string PlatinumColonyOption_Always_Description
        {
            get
            {
                return GetString("PlatinumColonyOption_Always_Description");
            }
        }
        
        /// <example>
        /// Always when using Prosperity
        /// </example>
        public static string PlatinumColonyOption_AlwaysWithProsperity
        {
            get
            {
                return GetString("PlatinumColonyOption_AlwaysWithProsperity");
            }
        }
        
        /// <example>
        /// If the selected set of Kingdom cards includes any from Prosperity, then always include Platinum and Colony.
        /// </example>
        public static string PlatinumColonyOption_AlwaysWithProsperity_Description
        {
            get
            {
                return GetString("PlatinumColonyOption_AlwaysWithProsperity_Description");
            }
        }
        
        /// <example>
        /// Never use them
        /// </example>
        public static string PlatinumColonyOption_Never
        {
            get
            {
                return GetString("PlatinumColonyOption_Never");
            }
        }
        
        /// <example>
        /// Never show Platinum and Colony in the list of required cards.
        /// </example>
        public static string PlatinumColonyOption_Never_Description
        {
            get
            {
                return GetString("PlatinumColonyOption_Never_Description");
            }
        }
        
        /// <example>
        /// Randomly select
        /// </example>
        public static string PlatinumColonyOption_Randomly
        {
            get
            {
                return GetString("PlatinumColonyOption_Randomly");
            }
        }
        
        /// <example>
        /// Using the Prosperity rules, randomly select a card from the set of Kingdom cards and if that card is from Prosperity, include Platinum/Colony.
        /// </example>
        public static string PlatinumColonyOption_Randomly_Description
        {
            get
            {
                return GetString("PlatinumColonyOption_Randomly_Description");
            }
        }
        
        /// <example>
        /// additional cards, tokens, etc.
        /// </example>
        public static string Results_ExtrasDesc
        {
            get
            {
                return GetString("Results_ExtrasDesc");
            }
        }
        
        /// <example>
        /// refresh
        /// </example>
        public static string Results_Refresh
        {
            get
            {
                return GetString("Results_Refresh");
            }
        }
        
        /// <example>
        /// regenerate
        /// </example>
        public static string Results_Regenerate
        {
            get
            {
                return GetString("Results_Regenerate");
            }
        }
        
        /// <example>
        /// save...
        /// </example>
        public static string Results_Save
        {
            get
            {
                return GetString("Results_Save");
            }
        }
        
        /// <example>
        /// sort cost
        /// </example>
        public static string Results_SortCost
        {
            get
            {
                return GetString("Results_SortCost");
            }
        }
        
        /// <example>
        /// sort name
        /// </example>
        public static string Results_SortName
        {
            get
            {
                return GetString("Results_SortName");
            }
        }
        
        /// <example>
        /// sort set
        /// </example>
        public static string Results_SortSet
        {
            get
            {
                return GetString("Results_SortSet");
            }
        }
        
        /// <example>
        /// Swipe to Replace
        ///Tap for Info
        /// </example>
        public static string Results_Tips
        {
            get
            {
                return GetString("Results_Tips");
            }
        }
        
        /// <example>
        /// results
        /// </example>
        public static string Results_Title
        {
            get
            {
                return GetString("Results_Title");
            }
        }
        
        /// <example>
        /// additional options
        /// </example>
        public static string Settings_AddnOptions
        {
            get
            {
                return GetString("Settings_AddnOptions");
            }
        }
        
        /// <example>
        /// Minimum Cards Per Set:
        /// </example>
        public static string Settings_MinCards
        {
            get
            {
                return GetString("Settings_MinCards");
            }
        }
        
        /// <example>
        /// Minimum cards per set in result:
        /// </example>
        public static string Settings_MinCardsDescription
        {
            get
            {
                return GetString("Settings_MinCardsDescription");
            }
        }
        
        /// <example>
        /// Pick if Platinum and Colony are used
        /// </example>
        public static string Settings_PickPlatinumColony
        {
            get
            {
                return GetString("Settings_PickPlatinumColony");
            }
        }
        
        /// <example>
        /// Pick if Shelters or Estates are used
        /// </example>
        public static string Settings_PickShelterOrEstate
        {
            get
            {
                return GetString("Settings_PickShelterOrEstate");
            }
        }
        
        /// <example>
        /// Plus Actions:
        /// </example>
        public static string Settings_PlusActions
        {
            get
            {
                return GetString("Settings_PlusActions");
            }
        }
        
        /// <example>
        /// Plus Buys:
        /// </example>
        public static string Settings_PlusBuys
        {
            get
            {
                return GetString("Settings_PlusBuys");
            }
        }
        
        /// <example>
        /// If there's an attack, require a defense
        /// </example>
        public static string Settings_RequireDefense
        {
            get
            {
                return GetString("Settings_RequireDefense");
            }
        }
        
        /// <example>
        /// Require a card that allows you to trash
        /// </example>
        public static string Settings_RequireTrash
        {
            get
            {
                return GetString("Settings_RequireTrash");
            }
        }
        
        /// <example>
        /// Show Basic Cards
        /// </example>
        public static string Settings_ShowBasicCards
        {
            get
            {
                return GetString("Settings_ShowBasicCards");
            }
        }
        
        /// <example>
        /// Lists the required number of all of the basic cards based on the number of players selected in addition to the starting hand makeup.
        /// </example>
        public static string Settings_ShowBasicCards_Description
        {
            get
            {
                return GetString("Settings_ShowBasicCards_Description");
            }
        }
        
        /// <example>
        /// Show Required Mats and Tokens
        /// </example>
        public static string Settings_ShowExtras
        {
            get
            {
                return GetString("Settings_ShowExtras");
            }
        }
        
        /// <example>
        /// Always use them
        /// </example>
        public static string SheltersOption_Always
        {
            get
            {
                return GetString("SheltersOption_Always");
            }
        }
        
        /// <example>
        /// Always use Shelters instead of Estates in your starting hand.
        /// </example>
        public static string SheltersOption_Always_Description
        {
            get
            {
                return GetString("SheltersOption_Always_Description");
            }
        }
        
        /// <example>
        /// Always when using Dark Ages
        /// </example>
        public static string SheltersOption_AlwaysWithDarkAges
        {
            get
            {
                return GetString("SheltersOption_AlwaysWithDarkAges");
            }
        }
        
        /// <example>
        /// If the selected set of Kingdom cards includes any from Dark Ages, then always use Shelters instead of Estates.
        /// </example>
        public static string SheltersOption_AlwaysWithDarkAges_Description
        {
            get
            {
                return GetString("SheltersOption_AlwaysWithDarkAges_Description");
            }
        }
        
        /// <example>
        /// Never use them
        /// </example>
        public static string SheltersOption_Never
        {
            get
            {
                return GetString("SheltersOption_Never");
            }
        }
        
        /// <example>
        /// Never use Shelters instead of Estates.
        /// </example>
        public static string SheltersOption_Never_Description
        {
            get
            {
                return GetString("SheltersOption_Never_Description");
            }
        }
        
        /// <example>
        /// Randomly select
        /// </example>
        public static string SheltersOption_Randomly
        {
            get
            {
                return GetString("SheltersOption_Randomly");
            }
        }
        
        /// <example>
        /// Using the Dark Ages rules, randomly select a card from the set of Kingdom cards and if that card is from Dark Ages, use Shelters instead of Estates.
        /// </example>
        public static string SheltersOption_Randomly_Description
        {
            get
            {
                return GetString("SheltersOption_Randomly_Description");
            }
        }
        
        private static ResourceContext CreateContext()
        {
            var dispatcher = default(CoreDispatcher);
            var window = Window.Current;
            if ((window != null))
            {
                dispatcher = window.Dispatcher;
            }
            if ((dispatcher == null))
            {
                var mainView = CoreApplication.MainView;
                if ((mainView != null))
                {
                    dispatcher = mainView.Dispatcher;
                }
            }
            return CreateContext(dispatcher);
        }
        
        private static ResourceContext CreateContext(CoreDispatcher dispatcher)
        {
            if ((dispatcher != null))
            {
                if (dispatcher.HasThreadAccess)
                {
                    return ResourceContext.GetForCurrentView();
                }
                var cancellationTokenSource = new CancellationTokenSource();
                try
                {
                    var context = default(ResourceContext);
                    var action = dispatcher.RunAsync(CoreDispatcherPriority.High, () => context = ResourceContext.GetForCurrentView());
                    var task = WindowsRuntimeSystemExtensions.AsTask(action, cancellationTokenSource.Token);
                    // Runs into a 'timeout', when the 'main-thread' is blocked recently.
                    // Don't wait too long as there is an alternative way to retrieve an context (for independent use).
                    task.Wait(TimeSpan.FromSeconds(1));
                    cancellationTokenSource.Cancel();
                    if ((context != null))
                    {
                        return context;
                    }
                }
                finally
                {
                    cancellationTokenSource.Dispose();
                }
            }
            return ResourceContext.GetForViewIndependentUse();
        }
        
        public static ResourceMap CreateMap<T>()
            where T :  class
        {
            var applicationAssemblyName = Application.Current.GetType().GetTypeInfo().Assembly.GetName().Name;
            var type = typeof(T);
            var assemblyName = type.GetTypeInfo().Assembly.GetName().Name;
            string resourceName;
            if (applicationAssemblyName.Equals(assemblyName))
            {
                resourceName = type.Name;
            }
            else
            {
                resourceName = (assemblyName 
                            + ("/" + type.Name));
            }
            return ResourceManager.Current.MainResourceMap.GetSubtree(resourceName);
        }
        
        public static string GetString(string propertyName)
        {
            return Map.GetValue(propertyName, Context).ValueAsString;
        }
    }
}
