//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ben.Dominion.Resources
{
    using System;
    using System.Globalization;
    using Windows.ApplicationModel.Resources;
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    public class CardDataStrings
    {
        private static ResourceLoader loader = ResourceLoader.GetForViewIndependentUse("DominionCore/CardDataStrings");

        protected static string GetString(string key)
        {
            return loader.GetString(key);
        }

        public static CultureInfo Culture { get; set; }


        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_LocalizedCardsFileName
        {
            get
            {
                return GetString("Application_LocalizedCardsFileName");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adventures.
        /// </summary>
        public static string CardSet_Adventures
        {
            get
            {
                return GetString("CardSet_Adventures");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alchemy.
        /// </summary>
        public static string CardSet_Alchemy
        {
            get
            {
                return GetString("CardSet_Alchemy");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string CardSet_Base
        {
            get
            {
                return GetString("CardSet_Base");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cornucopia.
        /// </summary>
        public static string CardSet_Cornucopia
        {
            get
            {
                return GetString("CardSet_Cornucopia");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark Ages.
        /// </summary>
        public static string CardSet_DarkAges
        {
            get
            {
                return GetString("CardSet_DarkAges");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Guilds.
        /// </summary>
        public static string CardSet_Guilds
        {
            get
            {
                return GetString("CardSet_Guilds");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hinterlands.
        /// </summary>
        public static string CardSet_Hinterlands
        {
            get
            {
                return GetString("CardSet_Hinterlands");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Intrigue.
        /// </summary>
        public static string CardSet_Intrigue
        {
            get
            {
                return GetString("CardSet_Intrigue");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        public static string CardSet_Promo
        {
            get
            {
                return GetString("CardSet_Promo");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prosperity.
        /// </summary>
        public static string CardSet_Prosperity
        {
            get
            {
                return GetString("CardSet_Prosperity");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seaside.
        /// </summary>
        public static string CardSet_Seaside
        {
            get
            {
                return GetString("CardSet_Seaside");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string CardType_Action
        {
            get
            {
                return GetString("CardType_Action");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string CardType_Attack
        {
            get
            {
                return GetString("CardType_Attack");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        public static string CardType_Curse
        {
            get
            {
                return GetString("CardType_Curse");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string CardType_Duration
        {
            get
            {
                return GetString("CardType_Duration");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string CardType_Event
        {
            get
            {
                return GetString("CardType_Event");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        public static string CardType_Knight
        {
            get
            {
                return GetString("CardType_Knight");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Looter.
        /// </summary>
        public static string CardType_Looter
        {
            get
            {
                return GetString("CardType_Looter");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string CardType_Prize
        {
            get
            {
                return GetString("CardType_Prize");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reaction.
        /// </summary>
        public static string CardType_Reaction
        {
            get
            {
                return GetString("CardType_Reaction");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string CardType_Reserve
        {
            get
            {
                return GetString("CardType_Reserve");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ruins.
        /// </summary>
        public static string CardType_Ruins
        {
            get
            {
                return GetString("CardType_Ruins");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shelter.
        /// </summary>
        public static string CardType_Shelter
        {
            get
            {
                return GetString("CardType_Shelter");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Traveller.
        /// </summary>
        public static string CardType_Traveller
        {
            get
            {
                return GetString("CardType_Traveller");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Treasure.
        /// </summary>
        public static string CardType_Treasure
        {
            get
            {
                return GetString("CardType_Treasure");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        public static string CardType_Victory
        {
            get
            {
                return GetString("CardType_Victory");
            }
        }
    }
}