//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 08/10/2016 23:59:49
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Ben.Dominion.Resources
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Strings
    {
        
        private static ResourceLoader resourceLoader;
        
        static Strings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Strings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Strings");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Strings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Dominion Picker"
        /// </summary>
        public static string Application_Title
        {
            get
            {
                return resourceLoader.GetString("Application_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "additional options"
        /// </summary>
        public static string MainPage_AddnOptions
        {
            get
            {
                return resourceLoader.GetString("MainPage_AddnOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "create"
        /// </summary>
        public static string MainPage_Create
        {
            get
            {
                return resourceLoader.GetString("MainPage_Create");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "favorites"
        /// </summary>
        public static string MainPage_Favorites
        {
            get
            {
                return resourceLoader.GetString("MainPage_Favorites");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Enjoy a set? Save it so you can try it again!"
        /// </summary>
        public static string Favorites_SetsDesc
        {
            get
            {
                return resourceLoader.GetString("Favorites_SetsDesc");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Card Sets"
        /// </summary>
        public static string Favorites_SetsTitle
        {
            get
            {
                return resourceLoader.GetString("Favorites_SetsTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Save your settings to quickly reuse them later."
        /// </summary>
        public static string Favorites_SettingsDesc
        {
            get
            {
                return resourceLoader.GetString("Favorites_SettingsDesc");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Card Randomizers"
        /// </summary>
        public static string Favorites_SettingsTitle
        {
            get
            {
                return resourceLoader.GetString("Favorites_SettingsTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No favorite sets saved yet. Try using one of the randomizers above to create one."
        /// </summary>
        public static string Favorites_NoSets
        {
            get
            {
                return resourceLoader.GetString("Favorites_NoSets");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No favorite randomizers saved yet.  Check out the create page to add one."
        /// </summary>
        public static string Favorites_NoSettings
        {
            get
            {
                return resourceLoader.GetString("Favorites_NoSettings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Minimum Cards Per Set:"
        /// </summary>
        public static string Settings_MinCards
        {
            get
            {
                return resourceLoader.GetString("Settings_MinCards");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pick if Platinum and Colony are used"
        /// </summary>
        public static string Settings_PickPlatinumColony
        {
            get
            {
                return resourceLoader.GetString("Settings_PickPlatinumColony");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pick if Shelters or Estates are used"
        /// </summary>
        public static string Settings_PickShelterOrEstate
        {
            get
            {
                return resourceLoader.GetString("Settings_PickShelterOrEstate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Plus Actions:"
        /// </summary>
        public static string Settings_PlusActions
        {
            get
            {
                return resourceLoader.GetString("Settings_PlusActions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Plus Buys:"
        /// </summary>
        public static string Settings_PlusBuys
        {
            get
            {
                return resourceLoader.GetString("Settings_PlusBuys");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If there's an attack, require a defense"
        /// </summary>
        public static string Settings_RequireDefense
        {
            get
            {
                return resourceLoader.GetString("Settings_RequireDefense");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Require a card that allows you to trash"
        /// </summary>
        public static string Settings_RequireTrash
        {
            get
            {
                return resourceLoader.GetString("Settings_RequireTrash");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Show Required Mats and Tokens"
        /// </summary>
        public static string Settings_ShowExtras
        {
            get
            {
                return resourceLoader.GetString("Settings_ShowExtras");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Minimum cards per set in result:"
        /// </summary>
        public static string Settings_MinCardsDescription
        {
            get
            {
                return resourceLoader.GetString("Settings_MinCardsDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string Application_LocalizedCardsFileName
        {
            get
            {
                return resourceLoader.GetString("Application_LocalizedCardsFileName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Card Details"
        /// </summary>
        public static string Config_CardData
        {
            get
            {
                return resourceLoader.GetString("Config_CardData");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string Config_CardDataDesc
        {
            get
            {
                return resourceLoader.GetString("Config_CardDataDesc");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Setting this will override the language used by Dominion Picker only and will not change the current system language.
        ///You must restart for this to take effect."
        /// </summary>
        public static string Config_LanguageDescription
        {
            get
            {
                return resourceLoader.GetString("Config_LanguageDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "language"
        /// </summary>
        public static string Config_Language
        {
            get
            {
                return resourceLoader.GetString("Config_Language");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Rules Text"
        /// </summary>
        public static string Config_RulesText
        {
            get
            {
                return resourceLoader.GetString("Config_RulesText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string Config_RulesTextDesc
        {
            get
            {
                return resourceLoader.GetString("Config_RulesTextDesc");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "settings"
        /// </summary>
        public static string Config_Title
        {
            get
            {
                return resourceLoader.GetString("Config_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "User Interface"
        /// </summary>
        public static string Config_UI
        {
            get
            {
                return resourceLoader.GetString("Config_UI");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string Config_UIDesc
        {
            get
            {
                return resourceLoader.GetString("Config_UIDesc");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "delete"
        /// </summary>
        public static string Favorites_Delete
        {
            get
            {
                return resourceLoader.GetString("Favorites_Delete");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "edit"
        /// </summary>
        public static string Favorites_Edit
        {
            get
            {
                return resourceLoader.GetString("Favorites_Edit");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "rename"
        /// </summary>
        public static string Favorites_Rename
        {
            get
            {
                return resourceLoader.GetString("Favorites_Rename");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Help/About"
        /// </summary>
        public static string Menu_About
        {
            get
            {
                return resourceLoader.GetString("Menu_About");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Black Market Deck"
        /// </summary>
        public static string Menu_BlackMarket
        {
            get
            {
                return resourceLoader.GetString("Menu_BlackMarket");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Card Lookup/Filter"
        /// </summary>
        public static string Menu_CardLookup
        {
            get
            {
                return resourceLoader.GetString("Menu_CardLookup");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Generate Set"
        /// </summary>
        public static string MainPage_GenerateButton
        {
            get
            {
                return resourceLoader.GetString("MainPage_GenerateButton");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Generating card set..."
        /// </summary>
        public static string MainPage_Generating
        {
            get
            {
                return resourceLoader.GetString("MainPage_Generating");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "reset"
        /// </summary>
        public static string MainPage_Reset
        {
            get
            {
                return resourceLoader.GetString("MainPage_Reset");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "save..."
        /// </summary>
        public static string MainPage_Save
        {
            get
            {
                return resourceLoader.GetString("MainPage_Save");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "additional options"
        /// </summary>
        public static string Settings_AddnOptions
        {
            get
            {
                return resourceLoader.GetString("Settings_AddnOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "additional cards, tokens, etc."
        /// </summary>
        public static string Results_ExtrasDesc
        {
            get
            {
                return resourceLoader.GetString("Results_ExtrasDesc");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Swipe to Replace
        ///Tap for Info"
        /// </summary>
        public static string Results_Tips
        {
            get
            {
                return resourceLoader.GetString("Results_Tips");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "results"
        /// </summary>
        public static string Results_Title
        {
            get
            {
                return resourceLoader.GetString("Results_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "rules"
        /// </summary>
        public static string Info_Rules
        {
            get
            {
                return resourceLoader.GetString("Info_Rules");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "set"
        /// </summary>
        public static string Info_Set
        {
            get
            {
                return resourceLoader.GetString("Info_Set");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Swipe to view
        ///other cards"
        /// </summary>
        public static string Info_Tips
        {
            get
            {
                return resourceLoader.GetString("Info_Tips");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "card info"
        /// </summary>
        public static string Info_Title
        {
            get
            {
                return resourceLoader.GetString("Info_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "type"
        /// </summary>
        public static string Info_Type
        {
            get
            {
                return resourceLoader.GetString("Info_Type");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "regenerate"
        /// </summary>
        public static string Results_Regenerate
        {
            get
            {
                return resourceLoader.GetString("Results_Regenerate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "save..."
        /// </summary>
        public static string Results_Save
        {
            get
            {
                return resourceLoader.GetString("Results_Save");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "sort cost"
        /// </summary>
        public static string Results_SortCost
        {
            get
            {
                return resourceLoader.GetString("Results_SortCost");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "sort name"
        /// </summary>
        public static string Results_SortName
        {
            get
            {
                return resourceLoader.GetString("Results_SortName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "sort set"
        /// </summary>
        public static string Results_SortSet
        {
            get
            {
                return resourceLoader.GetString("Results_SortSet");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Coin Token"
        /// </summary>
        public static string Dominion_CoinToken
        {
            get
            {
                return resourceLoader.GetString("Dominion_CoinToken");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Emargo Token"
        /// </summary>
        public static string Dominion_EmargoToken
        {
            get
            {
                return resourceLoader.GetString("Dominion_EmargoToken");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Island Mat"
        /// </summary>
        public static string Dominion_IslandMat
        {
            get
            {
                return resourceLoader.GetString("Dominion_IslandMat");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Mat"
        /// </summary>
        public static string Dominion_Mat
        {
            get
            {
                return resourceLoader.GetString("Dominion_Mat");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Native Village Mat"
        /// </summary>
        public static string Dominion_NativeVillageMat
        {
            get
            {
                return resourceLoader.GetString("Dominion_NativeVillageMat");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pirate Ship Mat"
        /// </summary>
        public static string Dominion_PirateMat
        {
            get
            {
                return resourceLoader.GetString("Dominion_PirateMat");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Token"
        /// </summary>
        public static string Dominion_Token
        {
            get
            {
                return resourceLoader.GetString("Dominion_Token");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "settings"
        /// </summary>
        public static string Application_Settings
        {
            get
            {
                return resourceLoader.GetString("Application_Settings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reset Filtered Cards"
        /// </summary>
        public static string Lookup_ResetFiltered
        {
            get
            {
                return resourceLoader.GetString("Lookup_ResetFiltered");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Filter by Name, Set, Type, Rules"
        /// </summary>
        public static string Lookup_SearchHint
        {
            get
            {
                return resourceLoader.GetString("Lookup_SearchHint");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Show Filtered Cards"
        /// </summary>
        public static string Lookup_ShowFiltered
        {
            get
            {
                return resourceLoader.GetString("Lookup_ShowFiltered");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Checked cards will
        ///never be picked"
        /// </summary>
        public static string Lookup_Tips
        {
            get
            {
                return resourceLoader.GetString("Lookup_Tips");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "card list"
        /// </summary>
        public static string Lookup_Title
        {
            get
            {
                return resourceLoader.GetString("Lookup_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "about"
        /// </summary>
        public static string About_About
        {
            get
            {
                return resourceLoader.GetString("About_About");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "changes"
        /// </summary>
        public static string About_Changes
        {
            get
            {
                return resourceLoader.GetString("About_Changes");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "help"
        /// </summary>
        public static string About_Help
        {
            get
            {
                return resourceLoader.GetString("About_Help");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "rate/review"
        /// </summary>
        public static string About_Rate
        {
            get
            {
                return resourceLoader.GetString("About_Rate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "rules"
        /// </summary>
        public static string About_Rules
        {
            get
            {
                return resourceLoader.GetString("About_Rules");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "update"
        /// </summary>
        public static string About_Update
        {
            get
            {
                return resourceLoader.GetString("About_Update");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string Menu_Settings
        {
            get
            {
                return resourceLoader.GetString("Menu_Settings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "black market"
        /// </summary>
        public static string BlackMarket_Title
        {
            get
            {
                return resourceLoader.GetString("BlackMarket_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "sets that I own"
        /// </summary>
        public static string Config_OwnedSets
        {
            get
            {
                return resourceLoader.GetString("Config_OwnedSets");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Specify which sets you own and would like to be able to pick from.  Sets not included here will never be used during selection or for any additional reasons such as the Black Market deck."
        /// </summary>
        public static string Config_OwnedSetsDescription
        {
            get
            {
                return resourceLoader.GetString("Config_OwnedSetsDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Language Options"
        /// </summary>
        public static string Config_LanguageOptions
        {
            get
            {
                return resourceLoader.GetString("Config_LanguageOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Picker Options"
        /// </summary>
        public static string Config_PickerOptions
        {
            get
            {
                return resourceLoader.GetString("Config_PickerOptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Download PDFs of the full versions of the Dominion Rules for each set.  The files are saved locally for quick access any time later."
        /// </summary>
        public static string About_RulesDescription
        {
            get
            {
                return resourceLoader.GetString("About_RulesDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "kingdom cards"
        /// </summary>
        public static string CardGroupType_KingdomCard
        {
            get
            {
                return resourceLoader.GetString("CardGroupType_KingdomCard");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "required by {0}"
        /// </summary>
        public static string CardGroupType_OtherRequired
        {
            get
            {
                return resourceLoader.GetString("CardGroupType_OtherRequired");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "strategy wiki"
        /// </summary>
        public static string Info_Wiki
        {
            get
            {
                return resourceLoader.GetString("Info_Wiki");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "bane for {0}"
        /// </summary>
        public static string CardGroupType_BaneRequired
        {
            get
            {
                return resourceLoader.GetString("CardGroupType_BaneRequired");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "SHOULD NOT USE"
        /// </summary>
        public static string CardGroupType_CurseRequired
        {
            get
            {
                return resourceLoader.GetString("CardGroupType_CurseRequired");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "selected because you're using Dark Ages"
        /// </summary>
        public static string CardGroupType_SelectedDarkAges
        {
            get
            {
                return resourceLoader.GetString("CardGroupType_SelectedDarkAges");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "selected because you're using Prosperity"
        /// </summary>
        public static string CardGroupType_SelectedProsperity
        {
            get
            {
                return resourceLoader.GetString("CardGroupType_SelectedProsperity");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "when to pick Platinum and Colony"
        /// </summary>
        public static string Config_PlatinumColonyOption
        {
            get
            {
                return resourceLoader.GetString("Config_PlatinumColonyOption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "when to pick Shelters or Estates"
        /// </summary>
        public static string Config_SheltersOption
        {
            get
            {
                return resourceLoader.GetString("Config_SheltersOption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always use them"
        /// </summary>
        public static string PlatinumColonyOption_Always
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_Always");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always show Platinum and Colony in the list of required cards."
        /// </summary>
        public static string PlatinumColonyOption_Always_Description
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_Always_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Never use them"
        /// </summary>
        public static string PlatinumColonyOption_Never
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_Never");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Never show Platinum and Colony in the list of required cards."
        /// </summary>
        public static string PlatinumColonyOption_Never_Description
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_Never_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Randomly select"
        /// </summary>
        public static string PlatinumColonyOption_Randomly
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_Randomly");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Using the Prosperity rules, randomly select a card from the set of Kingdom cards and if that card is from Prosperity, include Platinum/Colony."
        /// </summary>
        public static string PlatinumColonyOption_Randomly_Description
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_Randomly_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always use them"
        /// </summary>
        public static string SheltersOption_Always
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_Always");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always use Shelters instead of Estates in your starting hand."
        /// </summary>
        public static string SheltersOption_Always_Description
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_Always_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Never use them"
        /// </summary>
        public static string SheltersOption_Never
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_Never");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Never use Shelters instead of Estates."
        /// </summary>
        public static string SheltersOption_Never_Description
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_Never_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Randomly select"
        /// </summary>
        public static string SheltersOption_Randomly
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_Randomly");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Using the Dark Ages rules, randomly select a card from the set of Kingdom cards and if that card is from Dark Ages, use Shelters instead of Estates."
        /// </summary>
        public static string SheltersOption_Randomly_Description
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_Randomly_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always when using Prosperity"
        /// </summary>
        public static string PlatinumColonyOption_AlwaysWithProsperity
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_AlwaysWithProsperity");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If the selected set of Kingdom cards includes any from Prosperity, then always include Platinum and Colony."
        /// </summary>
        public static string PlatinumColonyOption_AlwaysWithProsperity_Description
        {
            get
            {
                return resourceLoader.GetString("PlatinumColonyOption_AlwaysWithProsperity_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always when using Dark Ages"
        /// </summary>
        public static string SheltersOption_AlwaysWithDarkAges
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_AlwaysWithDarkAges");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If the selected set of Kingdom cards includes any from Dark Ages, then always use Shelters instead of Estates."
        /// </summary>
        public static string SheltersOption_AlwaysWithDarkAges_Description
        {
            get
            {
                return resourceLoader.GetString("SheltersOption_AlwaysWithDarkAges_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Show Basic Cards"
        /// </summary>
        public static string Settings_ShowBasicCards
        {
            get
            {
                return resourceLoader.GetString("Settings_ShowBasicCards");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Lists the required number of all of the basic cards based on the number of players selected in addition to the starting hand makeup."
        /// </summary>
        public static string Settings_ShowBasicCards_Description
        {
            get
            {
                return resourceLoader.GetString("Settings_ShowBasicCards_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "events"
        /// </summary>
        public static string CardGroupType_Events
        {
            get
            {
                return resourceLoader.GetString("CardGroupType_Events");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "when to pick Events"
        /// </summary>
        public static string Config_EventsOption
        {
            get
            {
                return resourceLoader.GetString("Config_EventsOption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always select Events"
        /// </summary>
        public static string EventsOption_Always
        {
            get
            {
                return resourceLoader.GetString("EventsOption_Always");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Always when using a set with Events"
        /// </summary>
        public static string EventsOption_AlwaysWithSet
        {
            get
            {
                return resourceLoader.GetString("EventsOption_AlwaysWithSet");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If you are using a set that contains Events, the result will always include two randomly selected Events."
        /// </summary>
        public static string EventsOption_AlwaysWithSet_Description
        {
            get
            {
                return resourceLoader.GetString("EventsOption_AlwaysWithSet_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The result will always include two randomly selected Events."
        /// </summary>
        public static string EventsOption_Always_Description
        {
            get
            {
                return resourceLoader.GetString("EventsOption_Always_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Never select events"
        /// </summary>
        public static string EventsOption_Never
        {
            get
            {
                return resourceLoader.GetString("EventsOption_Never");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Never select any Events."
        /// </summary>
        public static string EventsOption_Never_Description
        {
            get
            {
                return resourceLoader.GetString("EventsOption_Never_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Randomly select "
        /// </summary>
        public static string EventsOption_Randomly
        {
            get
            {
                return resourceLoader.GetString("EventsOption_Randomly");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Randomly when using a set with Events"
        /// </summary>
        public static string EventsOption_RandomlyWithSet
        {
            get
            {
                return resourceLoader.GetString("EventsOption_RandomlyWithSet");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If you are using a set that contains Events, the result will include between zero and two randomly selected Events."
        /// </summary>
        public static string EventsOption_RandomlyWithSet_Description
        {
            get
            {
                return resourceLoader.GetString("EventsOption_RandomlyWithSet_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The result will include between zero and two randomly selected Events."
        /// </summary>
        public static string EventsOption_Randomly_Description
        {
            get
            {
                return resourceLoader.GetString("EventsOption_Randomly_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No Preference"
        /// </summary>
        public static string CardRequirementOption_NoPreference
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_NoPreference");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string CardRequirementOption_NoPreference_Description
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_NoPreference_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Prevent All"
        /// </summary>
        public static string CardRequirementOption_Prevent
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_Prevent");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Prevent All +2"
        /// </summary>
        public static string CardRequirementOption_PreventPlus2
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_PreventPlus2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string CardRequirementOption_PreventPlus2_Description
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_PreventPlus2_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string CardRequirementOption_Prevent_Description
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_Prevent_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Require At Least One"
        /// </summary>
        public static string CardRequirementOption_Require
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_Require");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Require At Least One +2"
        /// </summary>
        public static string CardRequirementOption_RequirePlus2
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_RequirePlus2");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string CardRequirementOption_RequirePlus2_Description
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_RequirePlus2_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string CardRequirementOption_Require_Description
        {
            get
            {
                return resourceLoader.GetString("CardRequirementOption_Require_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cards with +Action"
        /// </summary>
        public static string Config_PlusActions
        {
            get
            {
                return resourceLoader.GetString("Config_PlusActions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cards with +Buy"
        /// </summary>
        public static string Config_PlusBuys
        {
            get
            {
                return resourceLoader.GetString("Config_PlusBuys");
            }
        }
    }
}
