//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Dominion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardDataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardDataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ben.Dominion.Resources.CardDataStrings", typeof(CardDataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_LocalizedCardsFileName {
            get {
                return ResourceManager.GetString("Application_LocalizedCardsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy.
        /// </summary>
        public static string Set_Alchemy {
            get {
                return ResourceManager.GetString("Set_Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Set_Base {
            get {
                return ResourceManager.GetString("Set_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornucopia.
        /// </summary>
        public static string Set_Cornucopia {
            get {
                return ResourceManager.GetString("Set_Cornucopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Ages.
        /// </summary>
        public static string Set_DarkAges {
            get {
                return ResourceManager.GetString("Set_DarkAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilds.
        /// </summary>
        public static string Set_Guilds {
            get {
                return ResourceManager.GetString("Set_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinterlands.
        /// </summary>
        public static string Set_Hinterlands {
            get {
                return ResourceManager.GetString("Set_Hinterlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrigue.
        /// </summary>
        public static string Set_Intrigue {
            get {
                return ResourceManager.GetString("Set_Intrigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        public static string Set_Promo {
            get {
                return ResourceManager.GetString("Set_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosperity.
        /// </summary>
        public static string Set_Prosperity {
            get {
                return ResourceManager.GetString("Set_Prosperity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaside.
        /// </summary>
        public static string Set_Seaside {
            get {
                return ResourceManager.GetString("Set_Seaside", resourceCulture);
            }
        }
    }
}
