//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Dominion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ben.Dominion.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About_About {
            get {
                return ResourceManager.GetString("About_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changes.
        /// </summary>
        public static string About_Changes {
            get {
                return ResourceManager.GetString("About_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string About_Help {
            get {
                return ResourceManager.GetString("About_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate/review.
        /// </summary>
        public static string About_Rate {
            get {
                return ResourceManager.GetString("About_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rules.
        /// </summary>
        public static string About_Rules {
            get {
                return ResourceManager.GetString("About_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string About_Update {
            get {
                return ResourceManager.GetString("About_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_LocalizedCardsFileName {
            get {
                return ResourceManager.GetString("Application_LocalizedCardsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Application_Settings {
            get {
                return ResourceManager.GetString("Application_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominion Picker.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Details.
        /// </summary>
        public static string Config_CardData {
            get {
                return ResourceManager.GetString("Config_CardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Config_CardDataDesc {
            get {
                return ResourceManager.GetString("Config_CardDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Config_LangDesc {
            get {
                return ResourceManager.GetString("Config_LangDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string Config_Language {
            get {
                return ResourceManager.GetString("Config_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules Text.
        /// </summary>
        public static string Config_RulesText {
            get {
                return ResourceManager.GetString("Config_RulesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Config_RulesTextDesc {
            get {
                return ResourceManager.GetString("Config_RulesTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Config_Title {
            get {
                return ResourceManager.GetString("Config_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        public static string Config_UI {
            get {
                return ResourceManager.GetString("Config_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Config_UIDesc {
            get {
                return ResourceManager.GetString("Config_UIDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Token.
        /// </summary>
        public static string Dominion_CoinToken {
            get {
                return ResourceManager.GetString("Dominion_CoinToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emargo Token.
        /// </summary>
        public static string Dominion_EmargoToken {
            get {
                return ResourceManager.GetString("Dominion_EmargoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island Mat.
        /// </summary>
        public static string Dominion_IslandMat {
            get {
                return ResourceManager.GetString("Dominion_IslandMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat.
        /// </summary>
        public static string Dominion_Mat {
            get {
                return ResourceManager.GetString("Dominion_Mat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Village Mat.
        /// </summary>
        public static string Dominion_NativeVillageMat {
            get {
                return ResourceManager.GetString("Dominion_NativeVillageMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate Ship Mat.
        /// </summary>
        public static string Dominion_PirateMat {
            get {
                return ResourceManager.GetString("Dominion_PirateMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Dominion_Token {
            get {
                return ResourceManager.GetString("Dominion_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Favorites_Delete {
            get {
                return ResourceManager.GetString("Favorites_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Favorites_Edit {
            get {
                return ResourceManager.GetString("Favorites_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite sets saved yet. Try using one of the randomizers above to create one..
        /// </summary>
        public static string Favorites_NoSets {
            get {
                return ResourceManager.GetString("Favorites_NoSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite randomizers saved yet.  Check out the create page to add one..
        /// </summary>
        public static string Favorites_NoSettings {
            get {
                return ResourceManager.GetString("Favorites_NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string Favorites_Rename {
            get {
                return ResourceManager.GetString("Favorites_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy a set? Save it so you can try it again!.
        /// </summary>
        public static string Favorites_SetsDesc {
            get {
                return ResourceManager.GetString("Favorites_SetsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Sets.
        /// </summary>
        public static string Favorites_SetsTitle {
            get {
                return ResourceManager.GetString("Favorites_SetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your settings to quickly reuse them later..
        /// </summary>
        public static string Favorites_SettingsDesc {
            get {
                return ResourceManager.GetString("Favorites_SettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Randomizers.
        /// </summary>
        public static string Favorites_SettingsTitle {
            get {
                return ResourceManager.GetString("Favorites_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rules.
        /// </summary>
        public static string Info_Rules {
            get {
                return ResourceManager.GetString("Info_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        public static string Info_Set {
            get {
                return ResourceManager.GetString("Info_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe to view
        ///other cards.
        /// </summary>
        public static string Info_Tips {
            get {
                return ResourceManager.GetString("Info_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card info.
        /// </summary>
        public static string Info_Title {
            get {
                return ResourceManager.GetString("Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string Info_Type {
            get {
                return ResourceManager.GetString("Info_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Filtered Cards.
        /// </summary>
        public static string Lookup_ResetFiltered {
            get {
                return ResourceManager.GetString("Lookup_ResetFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Name, Set, Type, Rules.
        /// </summary>
        public static string Lookup_SearchHint {
            get {
                return ResourceManager.GetString("Lookup_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Filtered Cards.
        /// </summary>
        public static string Lookup_ShowFiltered {
            get {
                return ResourceManager.GetString("Lookup_ShowFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked cards will
        ///never be picked.
        /// </summary>
        public static string Lookup_Tips {
            get {
                return ResourceManager.GetString("Lookup_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card list.
        /// </summary>
        public static string Lookup_Title {
            get {
                return ResourceManager.GetString("Lookup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional options.
        /// </summary>
        public static string MainPage_AddnOptions {
            get {
                return ResourceManager.GetString("MainPage_AddnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string MainPage_Create {
            get {
                return ResourceManager.GetString("MainPage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string MainPage_Favorites {
            get {
                return ResourceManager.GetString("MainPage_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Set.
        /// </summary>
        public static string MainPage_GenerateButton {
            get {
                return ResourceManager.GetString("MainPage_GenerateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating card set....
        /// </summary>
        public static string MainPage_Generating {
            get {
                return ResourceManager.GetString("MainPage_Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string MainPage_Reset {
            get {
                return ResourceManager.GetString("MainPage_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save....
        /// </summary>
        public static string MainPage_Save {
            get {
                return ResourceManager.GetString("MainPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Market Deck.
        /// </summary>
        public static string Menu_BlackMarket {
            get {
                return ResourceManager.GetString("Menu_BlackMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Lookup/Filter.
        /// </summary>
        public static string Menu_CardLookup {
            get {
                return ResourceManager.GetString("Menu_CardLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional cards, tokens, etc..
        /// </summary>
        public static string Results_ExtrasDesc {
            get {
                return ResourceManager.GetString("Results_ExtrasDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regenerate.
        /// </summary>
        public static string Results_Regenerate {
            get {
                return ResourceManager.GetString("Results_Regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save....
        /// </summary>
        public static string Results_Save {
            get {
                return ResourceManager.GetString("Results_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort cost.
        /// </summary>
        public static string Results_SortCost {
            get {
                return ResourceManager.GetString("Results_SortCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort name.
        /// </summary>
        public static string Results_SortName {
            get {
                return ResourceManager.GetString("Results_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort set.
        /// </summary>
        public static string Results_SortSet {
            get {
                return ResourceManager.GetString("Results_SortSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe to Replace
        ///Tap for Info.
        /// </summary>
        public static string Results_Tips {
            get {
                return ResourceManager.GetString("Results_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string Results_Title {
            get {
                return ResourceManager.GetString("Results_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy.
        /// </summary>
        public static string Set_Alchemy {
            get {
                return ResourceManager.GetString("Set_Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Set_Base {
            get {
                return ResourceManager.GetString("Set_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornucopia.
        /// </summary>
        public static string Set_Cornucopia {
            get {
                return ResourceManager.GetString("Set_Cornucopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Ages.
        /// </summary>
        public static string Set_DarkAges {
            get {
                return ResourceManager.GetString("Set_DarkAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilds.
        /// </summary>
        public static string Set_Guilds {
            get {
                return ResourceManager.GetString("Set_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinterlands.
        /// </summary>
        public static string Set_Hinterlands {
            get {
                return ResourceManager.GetString("Set_Hinterlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrigue.
        /// </summary>
        public static string Set_Intrigue {
            get {
                return ResourceManager.GetString("Set_Intrigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        public static string Set_Promo {
            get {
                return ResourceManager.GetString("Set_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosperity.
        /// </summary>
        public static string Set_Prosperity {
            get {
                return ResourceManager.GetString("Set_Prosperity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaside.
        /// </summary>
        public static string Set_Seaside {
            get {
                return ResourceManager.GetString("Set_Seaside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional options.
        /// </summary>
        public static string Settings_AddnOptions {
            get {
                return ResourceManager.GetString("Settings_AddnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Cards Per Set:.
        /// </summary>
        public static string Settings_MinCards {
            get {
                return ResourceManager.GetString("Settings_MinCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum cards per set in result:.
        /// </summary>
        public static string Settings_MinCardsDescription {
            get {
                return ResourceManager.GetString("Settings_MinCardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick if Platinum and Colony are used.
        /// </summary>
        public static string Settings_PickPlatinumColony {
            get {
                return ResourceManager.GetString("Settings_PickPlatinumColony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick if Shelters or Estates are used.
        /// </summary>
        public static string Settings_PickShelterOrEstate {
            get {
                return ResourceManager.GetString("Settings_PickShelterOrEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus Actions:.
        /// </summary>
        public static string Settings_PlusActions {
            get {
                return ResourceManager.GetString("Settings_PlusActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus Buys:.
        /// </summary>
        public static string Settings_PlusBuys {
            get {
                return ResourceManager.GetString("Settings_PlusBuys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there&apos;s an attack, require a defense.
        /// </summary>
        public static string Settings_RequireDefense {
            get {
                return ResourceManager.GetString("Settings_RequireDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require a card that allows you to trash.
        /// </summary>
        public static string Settings_RequireTrash {
            get {
                return ResourceManager.GetString("Settings_RequireTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Required Mats and Tokens.
        /// </summary>
        public static string Settings_ShowExtras {
            get {
                return ResourceManager.GetString("Settings_ShowExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Type_Action {
            get {
                return ResourceManager.GetString("Type_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string Type_Attack {
            get {
                return ResourceManager.GetString("Type_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        public static string Type_Curse {
            get {
                return ResourceManager.GetString("Type_Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Type_Duration {
            get {
                return ResourceManager.GetString("Type_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        public static string Type_Knight {
            get {
                return ResourceManager.GetString("Type_Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looter.
        /// </summary>
        public static string Type_Looter {
            get {
                return ResourceManager.GetString("Type_Looter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string Type_Prize {
            get {
                return ResourceManager.GetString("Type_Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction.
        /// </summary>
        public static string Type_Reaction {
            get {
                return ResourceManager.GetString("Type_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins.
        /// </summary>
        public static string Type_Ruins {
            get {
                return ResourceManager.GetString("Type_Ruins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter.
        /// </summary>
        public static string Type_Shelter {
            get {
                return ResourceManager.GetString("Type_Shelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure.
        /// </summary>
        public static string Type_Treasure {
            get {
                return ResourceManager.GetString("Type_Treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        public static string Type_Victory {
            get {
                return ResourceManager.GetString("Type_Victory", resourceCulture);
            }
        }
    }
}
