//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Dominion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ben.Dominion.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominion Picker.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional options.
        /// </summary>
        public static string MainPage_AddnOptions {
            get {
                return ResourceManager.GetString("MainPage_AddnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string MainPage_Create {
            get {
                return ResourceManager.GetString("MainPage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favvorites.
        /// </summary>
        public static string MainPage_Favorites {
            get {
                return ResourceManager.GetString("MainPage_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy a set? Save it so you can try it again!.
        /// </summary>
        public static string MainPage_FavoriteSetsDescription {
            get {
                return ResourceManager.GetString("MainPage_FavoriteSetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Sets.
        /// </summary>
        public static string MainPage_FavoriteSetsTitle {
            get {
                return ResourceManager.GetString("MainPage_FavoriteSetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your settings to quickly reuse them later..
        /// </summary>
        public static string MainPage_FavoriteSettingsDescription {
            get {
                return ResourceManager.GetString("MainPage_FavoriteSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Randomizers.
        /// </summary>
        public static string MainPage_FavoriteSettingsTitle {
            get {
                return ResourceManager.GetString("MainPage_FavoriteSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite sets saved yet. Try using one of the randomizers above to create one..
        /// </summary>
        public static string MainPage_NoFavoriteSets {
            get {
                return ResourceManager.GetString("MainPage_NoFavoriteSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite randomizers saved yet.  Check out the create page to add one..
        /// </summary>
        public static string MainPage_NoFavoriteSettings {
            get {
                return ResourceManager.GetString("MainPage_NoFavoriteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy.
        /// </summary>
        public static string Set_Alchemy {
            get {
                return ResourceManager.GetString("Set_Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Set_Base {
            get {
                return ResourceManager.GetString("Set_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornucopia.
        /// </summary>
        public static string Set_Cornucopia {
            get {
                return ResourceManager.GetString("Set_Cornucopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Ages.
        /// </summary>
        public static string Set_DarkAges {
            get {
                return ResourceManager.GetString("Set_DarkAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilds.
        /// </summary>
        public static string Set_Guilds {
            get {
                return ResourceManager.GetString("Set_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinterlands.
        /// </summary>
        public static string Set_Hinterlands {
            get {
                return ResourceManager.GetString("Set_Hinterlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrigue.
        /// </summary>
        public static string Set_Intrigue {
            get {
                return ResourceManager.GetString("Set_Intrigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        public static string Set_Promo {
            get {
                return ResourceManager.GetString("Set_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosperity.
        /// </summary>
        public static string Set_Prosperity {
            get {
                return ResourceManager.GetString("Set_Prosperity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaside.
        /// </summary>
        public static string Set_Seaside {
            get {
                return ResourceManager.GetString("Set_Seaside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Cards Per Set:.
        /// </summary>
        public static string Settings_MinCards {
            get {
                return ResourceManager.GetString("Settings_MinCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum cards per set in result:.
        /// </summary>
        public static string Settings_MinCardsDescription {
            get {
                return ResourceManager.GetString("Settings_MinCardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Settings_PickPlatinumColony {
            get {
                return ResourceManager.GetString("Settings_PickPlatinumColony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Settings_PickShelterEstate {
            get {
                return ResourceManager.GetString("Settings_PickShelterEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus Actions:.
        /// </summary>
        public static string Settings_PlusActions {
            get {
                return ResourceManager.GetString("Settings_PlusActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus Buys:.
        /// </summary>
        public static string Settings_PlusBuys {
            get {
                return ResourceManager.GetString("Settings_PlusBuys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there&apos;s an attack, require a defense.
        /// </summary>
        public static string Settings_RequireDefense {
            get {
                return ResourceManager.GetString("Settings_RequireDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require a card that allows you to trash.
        /// </summary>
        public static string Settings_RequireTrash {
            get {
                return ResourceManager.GetString("Settings_RequireTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Extras.
        /// </summary>
        public static string Settings_ShowExtras {
            get {
                return ResourceManager.GetString("Settings_ShowExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Type_Action {
            get {
                return ResourceManager.GetString("Type_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string Type_Attack {
            get {
                return ResourceManager.GetString("Type_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        public static string Type_Curse {
            get {
                return ResourceManager.GetString("Type_Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Type_Duration {
            get {
                return ResourceManager.GetString("Type_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        public static string Type_Knight {
            get {
                return ResourceManager.GetString("Type_Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looter.
        /// </summary>
        public static string Type_Looter {
            get {
                return ResourceManager.GetString("Type_Looter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string Type_Prize {
            get {
                return ResourceManager.GetString("Type_Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction.
        /// </summary>
        public static string Type_Reaction {
            get {
                return ResourceManager.GetString("Type_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins.
        /// </summary>
        public static string Type_Ruins {
            get {
                return ResourceManager.GetString("Type_Ruins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter.
        /// </summary>
        public static string Type_Shelter {
            get {
                return ResourceManager.GetString("Type_Shelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure.
        /// </summary>
        public static string Type_Treasure {
            get {
                return ResourceManager.GetString("Type_Treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        public static string Type_Victory {
            get {
                return ResourceManager.GetString("Type_Victory", resourceCulture);
            }
        }
    }
}
