//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 09/11/2016 22:46:12
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Ben.Dominion.Resources
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class CardDataStrings
    {
        
        private static ResourceLoader resourceLoader;
        
        static CardDataStrings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(CardDataStrings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("CardDataStrings");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/CardDataStrings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to ""
        /// </summary>
        public static string Application_LocalizedCardsFileName
        {
            get
            {
                return resourceLoader.GetString("Application_LocalizedCardsFileName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Adventures"
        /// </summary>
        public static string CardSet_Adventures
        {
            get
            {
                return resourceLoader.GetString("CardSet_Adventures");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Alchemy"
        /// </summary>
        public static string CardSet_Alchemy
        {
            get
            {
                return resourceLoader.GetString("CardSet_Alchemy");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Base"
        /// </summary>
        public static string CardSet_Base
        {
            get
            {
                return resourceLoader.GetString("CardSet_Base");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cornucopia"
        /// </summary>
        public static string CardSet_Cornucopia
        {
            get
            {
                return resourceLoader.GetString("CardSet_Cornucopia");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Dark Ages"
        /// </summary>
        public static string CardSet_DarkAges
        {
            get
            {
                return resourceLoader.GetString("CardSet_DarkAges");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Empires"
        /// </summary>
        public static string CardSet_Empires
        {
            get
            {
                return resourceLoader.GetString("CardSet_Empires");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Guilds"
        /// </summary>
        public static string CardSet_Guilds
        {
            get
            {
                return resourceLoader.GetString("CardSet_Guilds");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hinterlands"
        /// </summary>
        public static string CardSet_Hinterlands
        {
            get
            {
                return resourceLoader.GetString("CardSet_Hinterlands");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Intrigue"
        /// </summary>
        public static string CardSet_Intrigue
        {
            get
            {
                return resourceLoader.GetString("CardSet_Intrigue");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Promo"
        /// </summary>
        public static string CardSet_Promo
        {
            get
            {
                return resourceLoader.GetString("CardSet_Promo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Prosperity"
        /// </summary>
        public static string CardSet_Prosperity
        {
            get
            {
                return resourceLoader.GetString("CardSet_Prosperity");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Seaside"
        /// </summary>
        public static string CardSet_Seaside
        {
            get
            {
                return resourceLoader.GetString("CardSet_Seaside");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Action"
        /// </summary>
        public static string CardType_Action
        {
            get
            {
                return resourceLoader.GetString("CardType_Action");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Attack"
        /// </summary>
        public static string CardType_Attack
        {
            get
            {
                return resourceLoader.GetString("CardType_Attack");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Curse"
        /// </summary>
        public static string CardType_Curse
        {
            get
            {
                return resourceLoader.GetString("CardType_Curse");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Duration"
        /// </summary>
        public static string CardType_Duration
        {
            get
            {
                return resourceLoader.GetString("CardType_Duration");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Event"
        /// </summary>
        public static string CardType_Event
        {
            get
            {
                return resourceLoader.GetString("CardType_Event");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Knight"
        /// </summary>
        public static string CardType_Knight
        {
            get
            {
                return resourceLoader.GetString("CardType_Knight");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Landmark"
        /// </summary>
        public static string CardType_Landmark
        {
            get
            {
                return resourceLoader.GetString("CardType_Landmark");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Looter"
        /// </summary>
        public static string CardType_Looter
        {
            get
            {
                return resourceLoader.GetString("CardType_Looter");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Prize"
        /// </summary>
        public static string CardType_Prize
        {
            get
            {
                return resourceLoader.GetString("CardType_Prize");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reaction"
        /// </summary>
        public static string CardType_Reaction
        {
            get
            {
                return resourceLoader.GetString("CardType_Reaction");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reserve"
        /// </summary>
        public static string CardType_Reserve
        {
            get
            {
                return resourceLoader.GetString("CardType_Reserve");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Ruins"
        /// </summary>
        public static string CardType_Ruins
        {
            get
            {
                return resourceLoader.GetString("CardType_Ruins");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Shelter"
        /// </summary>
        public static string CardType_Shelter
        {
            get
            {
                return resourceLoader.GetString("CardType_Shelter");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Traveller"
        /// </summary>
        public static string CardType_Traveller
        {
            get
            {
                return resourceLoader.GetString("CardType_Traveller");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Treasure"
        /// </summary>
        public static string CardType_Treasure
        {
            get
            {
                return resourceLoader.GetString("CardType_Treasure");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Victory"
        /// </summary>
        public static string CardType_Victory
        {
            get
            {
                return resourceLoader.GetString("CardType_Victory");
            }
        }
    }
}
