//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Dominion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardDataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardDataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ben.Dominion.Resources.CardDataStrings", typeof(CardDataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_LocalizedCardsFileName {
            get {
                return ResourceManager.GetString("Application_LocalizedCardsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventures.
        /// </summary>
        public static string CardSet_Adventures {
            get {
                return ResourceManager.GetString("CardSet_Adventures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy.
        /// </summary>
        public static string CardSet_Alchemy {
            get {
                return ResourceManager.GetString("CardSet_Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string CardSet_Base {
            get {
                return ResourceManager.GetString("CardSet_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornucopia.
        /// </summary>
        public static string CardSet_Cornucopia {
            get {
                return ResourceManager.GetString("CardSet_Cornucopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Ages.
        /// </summary>
        public static string CardSet_DarkAges {
            get {
                return ResourceManager.GetString("CardSet_DarkAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilds.
        /// </summary>
        public static string CardSet_Guilds {
            get {
                return ResourceManager.GetString("CardSet_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinterlands.
        /// </summary>
        public static string CardSet_Hinterlands {
            get {
                return ResourceManager.GetString("CardSet_Hinterlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrigue.
        /// </summary>
        public static string CardSet_Intrigue {
            get {
                return ResourceManager.GetString("CardSet_Intrigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        public static string CardSet_Promo {
            get {
                return ResourceManager.GetString("CardSet_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosperity.
        /// </summary>
        public static string CardSet_Prosperity {
            get {
                return ResourceManager.GetString("CardSet_Prosperity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaside.
        /// </summary>
        public static string CardSet_Seaside {
            get {
                return ResourceManager.GetString("CardSet_Seaside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string CardType_Action {
            get {
                return ResourceManager.GetString("CardType_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string CardType_Attack {
            get {
                return ResourceManager.GetString("CardType_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        public static string CardType_Curse {
            get {
                return ResourceManager.GetString("CardType_Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string CardType_Duration {
            get {
                return ResourceManager.GetString("CardType_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string CardType_Event {
            get {
                return ResourceManager.GetString("CardType_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        public static string CardType_Knight {
            get {
                return ResourceManager.GetString("CardType_Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looter.
        /// </summary>
        public static string CardType_Looter {
            get {
                return ResourceManager.GetString("CardType_Looter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string CardType_Prize {
            get {
                return ResourceManager.GetString("CardType_Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction.
        /// </summary>
        public static string CardType_Reaction {
            get {
                return ResourceManager.GetString("CardType_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string CardType_Reserve {
            get {
                return ResourceManager.GetString("CardType_Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins.
        /// </summary>
        public static string CardType_Ruins {
            get {
                return ResourceManager.GetString("CardType_Ruins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter.
        /// </summary>
        public static string CardType_Shelter {
            get {
                return ResourceManager.GetString("CardType_Shelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveller.
        /// </summary>
        public static string CardType_Traveller {
            get {
                return ResourceManager.GetString("CardType_Traveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure.
        /// </summary>
        public static string CardType_Treasure {
            get {
                return ResourceManager.GetString("CardType_Treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        public static string CardType_Victory {
            get {
                return ResourceManager.GetString("CardType_Victory", resourceCulture);
            }
        }
    }
}
